"""Guardrail: signed steward content must keep its canonical bytes forever.

``canonical_json_bytes`` is a bare ``model_dump(mode="json")``, and the signed envelopes
recompute their digest on every ``model_validate``. Adding a field to any content model in
this graph -- including an optional one defaulting to ``None``, which still serializes --
silently rewrites the canonical bytes of already-signed records, and every stored
authority binding, materialization report and corpus release candidate stops loading.

The fixtures here are byte-frozen copies of real artifacts from the WHO SMART HIV
materialization run, lifted verbatim out of the content-addressed artifact store. They are
never regenerated by application code, so they cannot drift with the schemas they pin.

See docs/narrative-only-materialization.md for why this gates the narrative-only work.
"""

import hashlib
import json
import os
from pathlib import Path

import pytest

from app.corpus_steward.materialization_schemas import (
    AssetCoverage,
    AuthorityAssetBinding,
    AuthorityBindingContent,
    CorpusReleaseCandidateContent,
    EvidenceCoverageReport,
    MaterializationReport,
    MaterializationReportContent,
    MaterializedEvidenceArtifactEntry,
    MaterializedEvidenceContent,
    MaterializedEvidenceRecord,
    SignedAuthorityBinding,
    SignedCorpusReleaseCandidate,
    StructuralMappingAttachment,
)
from app.corpus_steward.schemas import AssetLicensingPolicy, VerifiedAttestationReference
from app.schemas.corpus import canonical_json_bytes, canonical_sha256

FIXTURE_DIR = Path(__file__).parents[1] / "fixtures" / "steward_history"
MANIFEST = json.loads((FIXTURE_DIR / "MANIFEST.json").read_text(encoding="utf-8"))

DEFAULT_ARTIFACT_STORE = Path(__file__).parents[4] / "data" / "local" / "steward-artifacts"
ARTIFACT_STORE = Path(
    os.environ.get("MED_RAG_STEWARD_ARTIFACT_STORE", str(DEFAULT_ARTIFACT_STORE))
)

# Digests of the real WHO SMART HIV materialization outputs. These are history: a change
# that moves any of them has invalidated signed content that can never be re-signed.
MATERIALIZATION_RUN_ID = "MAT_213e6d22e22dc92bd429920e87a2beef"
AUTHORITY_BINDING_SHA256 = "c0cf9b36b16e9accbd5cc3091016a679965dd38fd3fbb385f2e62b23d2043c0e"
MATERIALIZATION_REPORT_SHA256 = (
    "26bf4f8f6ea073d0db1023fa78d5790c0a615d1517f0a5baefeeb4db4b09f512"
)
MATERIALIZATION_REPORT_ARTIFACT_SHA256 = (
    "e972cb372cb15b73abadd6306f016e52fd3483a1bb1960ba21337adb86e2105b"
)

_ENVELOPES = {
    "SignedAuthorityBinding": SignedAuthorityBinding,
    "MaterializedEvidenceRecord": MaterializedEvidenceRecord,
}

# Every content model reachable from a signed steward envelope, with the exact field names
# its canonical serialization committed to. A new field here is not a compatible change.
FROZEN_MODEL_FIELDS: dict[str, tuple[str, ...]] = {
    "AssetCoverage": (
        "asset_id",
        "complete",
        "empty_source_units",
        "evidence_ids",
        "expected_source_units",
        "materialized_source_units",
        "source_artifact_sha256",
    ),
    "AssetLicensingPolicy": (
        "acquisition_allowed",
        "asset_id",
        "asset_kind",
        "credential_reference",
        "evidence_materialization_allowed",
        "license_id",
        "notes",
        "policy_url",
        "redistribution_allowed",
        "render_allowed",
        "source_declared_license_id",
    ),
    "AuthorityAssetBinding": (
        "asset_id",
        "authority_role",
        "authorized_use",
        "clinical_content_promotable",
        "experimental",
        "licensing",
        "lifecycle_status",
        "media_type",
        "source_artifact_sha256",
        "source_uri",
        "title",
    ),
    "AuthorityBindingContent": (
        "assets",
        "bound_at",
        "controlling_source_id",
        "input_closure_sha256",
        "licensing_trust_root_sha256",
        "materialization_run_id",
        "reconciliation_candidate_id",
        "schema_version",
        "structured_companion_id",
        "structured_report_sha256",
        "trust_root_id",
        "trust_root_sha256",
    ),
    "CorpusReleaseCandidateContent": (
        "authority_binding_sha256",
        "corpus_release_candidate_id",
        "created_at",
        "evidence_entries",
        "materialization_report_sha256",
        "materialization_run_id",
        "qa_required",
        "reconciliation_candidate_id",
        "retrieval_eligible",
        "schema_version",
        "trust_root_sha256",
    ),
    "EvidenceCoverageReport": (
        "assets",
        "authority_binding_sha256",
        "complete",
        "evidence_count",
        "expected_asset_ids",
    ),
    "MaterializationReport": ("content", "report_sha256"),
    "MaterializationReportContent": (
        "authority_binding",
        "blockers",
        "completed_at",
        "coverage",
        "evidence",
        "materialization_run_id",
        "materializer_name",
        "materializer_version",
        "ready_for_qa",
        "reconciliation_candidate_id",
        "schema_version",
        "structural_mapping",
    ),
    "MaterializedEvidenceArtifactEntry": (
        "artifact_sha256",
        "asset_id",
        "evidence_id",
        "evidence_sha256",
        "source_artifact_sha256",
        "source_unit_id",
    ),
    "MaterializedEvidenceContent": (
        "anchors",
        "asset_id",
        "authority_binding_sha256",
        "authority_role",
        "content_exact",
        "content_search",
        "evidence_id",
        "jurisdiction",
        "language",
        "lifecycle_status",
        "materialization_run_id",
        "publisher_id",
        "qa_status",
        "render_allowed",
        "schema_version",
        "source_artifact_sha256",
        "source_title",
        "source_unit_id",
        "source_version_id",
    ),
    "MaterializedEvidenceRecord": ("content", "evidence_sha256"),
    "SignedAuthorityBinding": ("attestation", "binding_sha256", "content"),
    "SignedCorpusReleaseCandidate": ("attestation", "candidate_sha256", "content"),
    "StructuralMappingAttachment": (
        "asset_id",
        "authorized_use",
        "clinical_content_included",
        "implementation_guide_experimental",
        "resource_count",
        "resource_inventory_sha256",
        "structured_run_id",
        "structured_report_sha256",
    ),
    "VerifiedAttestationReference": (
        "attestation_id",
        "predicate_type",
        "purpose",
        "signature_sha256",
        "signer_identity",
        "signing_key_id",
        "statement_sha256",
        "verified_at",
    ),
}

_MODELS = {
    "AssetCoverage": AssetCoverage,
    "AssetLicensingPolicy": AssetLicensingPolicy,
    "AuthorityAssetBinding": AuthorityAssetBinding,
    "AuthorityBindingContent": AuthorityBindingContent,
    "CorpusReleaseCandidateContent": CorpusReleaseCandidateContent,
    "EvidenceCoverageReport": EvidenceCoverageReport,
    "MaterializationReport": MaterializationReport,
    "MaterializationReportContent": MaterializationReportContent,
    "MaterializedEvidenceArtifactEntry": MaterializedEvidenceArtifactEntry,
    "MaterializedEvidenceContent": MaterializedEvidenceContent,
    "MaterializedEvidenceRecord": MaterializedEvidenceRecord,
    "SignedAuthorityBinding": SignedAuthorityBinding,
    "SignedCorpusReleaseCandidate": SignedCorpusReleaseCandidate,
    "StructuralMappingAttachment": StructuralMappingAttachment,
    "VerifiedAttestationReference": VerifiedAttestationReference,
}

_ENTRY_IDS = [entry["file"] for entry in MANIFEST["entries"]]


def _entry(file_name: str) -> dict[str, object]:
    return next(item for item in MANIFEST["entries"] if item["file"] == file_name)


@pytest.mark.parametrize("file_name", _ENTRY_IDS)
def test_frozen_fixture_bytes_match_their_artifact_digest(file_name: str) -> None:
    """The fixtures carry self-verifying provenance: content address over their own bytes."""

    entry = _entry(file_name)
    raw = (FIXTURE_DIR / file_name).read_bytes()

    assert len(raw) == entry["byte_size"]
    assert hashlib.sha256(raw).hexdigest() == entry["artifact_sha256"]


@pytest.mark.parametrize("file_name", _ENTRY_IDS)
def test_stored_envelopes_still_round_trip_to_identical_canonical_bytes(file_name: str) -> None:
    entry = _entry(file_name)
    raw = (FIXTURE_DIR / file_name).read_bytes()
    envelope = _ENVELOPES[str(entry["model"])].model_validate(json.loads(raw))

    assert canonical_sha256(envelope.content) == entry["content_sha256"]
    assert canonical_json_bytes(envelope) == raw


def test_stored_authority_binding_digest_is_unchanged() -> None:
    raw = (FIXTURE_DIR / "authority-binding.json").read_bytes()
    binding = SignedAuthorityBinding.model_validate(json.loads(raw))

    assert binding.content.materialization_run_id == MATERIALIZATION_RUN_ID
    assert binding.binding_sha256 == AUTHORITY_BINDING_SHA256
    assert canonical_sha256(binding.content) == AUTHORITY_BINDING_SHA256
    assert binding.attestation.statement_sha256 == AUTHORITY_BINDING_SHA256
    assert canonical_json_bytes(binding) == raw


@pytest.mark.skipif(
    not (ARTIFACT_STORE / "sha256").is_dir(),
    reason=(
        "local steward artifact store is absent; the 53 MB materialization report cannot be "
        "vendored into the repository. Set MED_RAG_STEWARD_ARTIFACT_STORE to verify it."
    ),
)
def test_stored_materialization_report_digest_is_unchanged() -> None:
    matches = list(ARTIFACT_STORE.rglob(f"{MATERIALIZATION_REPORT_ARTIFACT_SHA256}.blob"))
    if not matches:
        pytest.skip("materialization report artifact is not preserved in this artifact store")
    raw = matches[0].read_bytes()

    assert hashlib.sha256(raw).hexdigest() == MATERIALIZATION_REPORT_ARTIFACT_SHA256

    report = MaterializationReport.model_validate(json.loads(raw))

    assert report.content.materialization_run_id == MATERIALIZATION_RUN_ID
    assert report.report_sha256 == MATERIALIZATION_REPORT_SHA256
    assert canonical_sha256(report.content) == MATERIALIZATION_REPORT_SHA256
    assert canonical_json_bytes(report) == raw
    # The stored report predates compact evidence entries. It survives only because the
    # field was widened by union rather than replaced -- the precedent the narrative-only
    # binding follows.
    assert all(isinstance(item, MaterializedEvidenceRecord) for item in report.content.evidence)
    assert report.content.authority_binding.binding_sha256 == AUTHORITY_BINDING_SHA256


@pytest.mark.parametrize("model_name", sorted(FROZEN_MODEL_FIELDS))
def test_signed_content_models_have_not_gained_or_lost_fields(model_name: str) -> None:
    """Covers the models the vendored fixtures cannot reach, in every environment."""

    actual = tuple(sorted(_MODELS[model_name].model_fields))

    assert actual == tuple(sorted(FROZEN_MODEL_FIELDS[model_name])), (
        f"{model_name} changed shape. Every field of this model is committed to signed, "
        "content-addressed history; an added field re-serializes records that can never be "
        "re-signed. Widen an existing field by union instead -- see "
        "docs/narrative-only-materialization.md."
    )
